spring:
  application:
    name: backend
  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: 'password'
    url: 'jdbc:postgresql://localhost:5432/postgres'
  jpa:
    hibernate:
      ddl-auto: create
jwt:
  secret: "dd36173c67426d94abe65220651a7b7f5e14e4b3191d2677f3dcb0161661a163"
  expirationInMinutes: 60

server:
  port: 8085

logging:
  level:
    org:
      springframework:
        security: DEBUG